spring:
  datasource:
    url: jdbc:h2:mem:testdb

#    url: jdbc:h2:./devdb
#  jpa:
#    hibernate:
#      ddl-auto: update


  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none